// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNR8s2g46DvmfoedYgfQ3w0loKGWyhUQ',
    appId: '1:607247914246:web:f40d35ef736240cec1ba87',
    messagingSenderId: '607247914246',
    projectId: 'winpoi-ba357',
    authDomain: 'winpoi-ba357.firebaseapp.com',
    storageBucket: 'winpoi-ba357.firebasestorage.app',
    measurementId: 'G-CKN1J3QH70',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrDTgGN4dHTeP81ITbZNZlSA7XIEPS94',
    appId: '1:607247914246:ios:84b824b13efb800ec1ba87',
    messagingSenderId: '607247914246',
    projectId: 'winpoi-ba357',
    storageBucket: 'winpoi-ba357.firebasestorage.app',
    iosBundleId: 'com.example.winpoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrDTgGN4dHTeP81ITbZNZlSA7XIEPS94',
    appId: '1:607247914246:ios:84b824b13efb800ec1ba87',
    messagingSenderId: '607247914246',
    projectId: 'winpoi-ba357',
    storageBucket: 'winpoi-ba357.firebasestorage.app',
    iosBundleId: 'com.example.winpoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJNR8s2g46DvmfoedYgfQ3w0loKGWyhUQ',
    appId: '1:607247914246:web:60f115b39819328ac1ba87',
    messagingSenderId: '607247914246',
    projectId: 'winpoi-ba357',
    authDomain: 'winpoi-ba357.firebaseapp.com',
    storageBucket: 'winpoi-ba357.firebasestorage.app',
    measurementId: 'G-P4E8FWJ09N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALIbFc-SSObzaTHD5Ux9EPByYS4eJaE2c',
    appId: '1:607247914246:android:156a8869ae34eba2c1ba87',
    messagingSenderId: '607247914246',
    projectId: 'winpoi-ba357',
    storageBucket: 'winpoi-ba357.firebasestorage.app',
  );

}